---

- name: Perform Ping and Save Results
  gather_facts: false
  hosts: all
  tasks:

    - name: Ping Servers
      ansible.builtin.ping: 
        count: 3
      register: ping_result

    - name:  Save Ping Results to File
      ansible.builtin.copy:
        content:
"{{ ping_results.stdout }}
        dest: ping-output.txt
  

